apiVersion: apps/v1

kind: Deployment

metadata:
  name: redis

spec:
  selector:
    matchLabels:
      app: redis
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 0
           maxUnavailable: 100%    
  replicas: 2
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: samarthr8/zocket:redis
          resources:
            requests:
              memory: "100Mi"
              cpu: 0.1
            limits:
              memory: "200Mi"
              cpu: 0.2
---

apiVersion: v1

kind: Service

metadata:
  name: redis
  labels:
    app: redis

spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: "redis-service"
    protocol: TCP
    port: 6379
    targetPort: 6379
