apiVersion: apps/v1

kind: Deployment

metadata:
  name: redis

spec:
  selector:
    matchLabels:
      app: redis
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 0
           maxUnavailable: 100%    
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: samarthr8/zocket:redis
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "50Mi"
              cpu: "50m"
---

apiVersion: v1

kind: Service

metadata:
  name: redis
  labels:
    app: redis

spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: "redis-service"
    protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
