apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 50%
  selector:
    matchLabels:
      app: vote
  replicas: 2
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: samarthr8/zocket:vote
          resources:
            requests:
              memory: "100Mi"
              cpu: 0.1
            limits:
              memory: "200Mi"
              cpu: 0.2
---

apiVersion: v1

kind: Service

metadata:
  name: vote
  labels:
    app: vote

spec:
  selector:
    app: vote
  type: LoadBalancer
  ports:
  - name: "vote-service"
    protocol: TCP
    port: 5000
    targetPort: 80
